version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8081:8081'
    volumes:
      - /app/node_modules
      - .:/app

    stdin_open: true
    command: ['npm', 'run', 'start']
